Fix improper member name
The proper member name is _factory. This was causing an attribute error
on close:

File "/xxx/site-packages/gpiozero/pins/pigpio.py", line 499, in close
    self.factory.release_all(self)
AttributeError: 'PiGPIOSoftwareSPI' object has no attribute 'factory'